development:
  sessions:
    default:
      database: tcc_development
      hosts:
        - 192.168.56.99:27017

test:
  sessions:
    default:
      database: tcc_test
      hosts:
        - 192.168.56.99:27017


production:
  sessions:
    default:
      uri: mongodb://heroku_app35360665:vhu086cjpjufmvk5jh4ejmmhou@ds053439.mongolab.com:53439/heroku_app35360665
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10