development:
  clients:
    default:
      database: tcc_development
      hosts:
        - 127.0.0.1:27017

test:
  clients:
    default:
      database: tcc_test
      hosts:
        - 127.0.0.1:27017


production:
  clients:
    default:
      uri: mongodb://heroku_app35360665:vhu086cjpjufmvk5jh4ejmmhou@ds053439.mongolab.com:53439/heroku_app35360665
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10